[package]
name = "notification"
version = "0.1.0"
authors = ["jxw3ng <jx.w@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac-notification-sys = "0.3"
open = "~1.4"
